# Import Dependencies

In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv("Twitter data.csv")

In [3]:
dataset.head()

2401  Borderlands  Positive  \
0  2401  Borderlands  Positive   
1  2401  Borderlands  Positive   
2  2401  Borderlands  Positive   
3  2401  Borderlands  Positive   
4  2401  Borderlands  Positive   

  im getting on borderlands and i will murder you all ,  
0  I am coming to the borders and I will kill you...     
1  im getting on borderlands and i will kill you ...     
2  im coming on borderlands and i will murder you...     
3  im getting on borderlands 2 and i will murder ...     
4  im getting into borderlands and i can murder y...

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74681 entries, 0 to 74680
Data columns (total 4 columns):
 #   Column                                                 Non-Null Count  Dtype 
---  ------                                                 --------------  ----- 
 0   2401                                                   74681 non-null  int64 
 1   Borderlands                                            74681 non-null  object
 2   Positive                                               74681 non-null  object
 3   im getting on borderlands and i will murder you all ,  73995 non-null  object
dtypes: int64(1), object(3)
memory usage: 2.3+ MB


In [5]:
dataset.shape

(74681, 4)

In [6]:
dataset["Positive"].value_counts()

Negative      22542
Positive      20831
Neutral       18318
Irrelevant    12990
Name: Positive, dtype: int64

In [7]:
dataset.isnull().sum()

2401                                                       0
Borderlands                                                0
Positive                                                   0
im getting on borderlands and i will murder you all ,    686
dtype: int64

In [8]:
dataset.columns

Index(['2401', 'Borderlands', 'Positive',
       'im getting on borderlands and i will murder you all ,'],
      dtype='object')

In [9]:
df = pd.DataFrame(dataset)
data = df.columns.tolist()
data[data.index('Positive')] = 'Review'
data[data.index('im getting on borderlands and i will murder you all ,')] = 'Text'

In [10]:
df.columns = data

In [11]:
df.columns

Index(['2401', 'Borderlands', 'Review', 'Text'], dtype='object')

In [12]:
dataset = df.drop(columns = ["2401","Borderlands"])

In [13]:
dataset.head()

Review                                               Text
0  Positive  I am coming to the borders and I will kill you...
1  Positive  im getting on borderlands and i will kill you ...
2  Positive  im coming on borderlands and i will murder you...
3  Positive  im getting on borderlands 2 and i will murder ...
4  Positive  im getting into borderlands and i can murder y...

In [14]:
dataset.shape

(74681, 2)

In [15]:
dataset.isnull().sum()

Review      0
Text      686
dtype: int64

In [16]:
dataset["Text"].dropna()

0        I am coming to the borders and I will kill you...
1        im getting on borderlands and i will kill you ...
2        im coming on borderlands and i will murder you...
3        im getting on borderlands 2 and i will murder ...
4        im getting into borderlands and i can murder y...
                               ...                        
74676    Just realized that the Windows partition of my...
74677    Just realized that my Mac window partition is ...
74678    Just realized the windows partition of my Mac ...
74679    Just realized between the windows partition of...
74680    Just like the windows partition of my Mac is l...
Name: Text, Length: 73995, dtype: object

In [17]:
dataset.shape

(74681, 2)

In [18]:
from sklearn.preprocessing import LabelEncoder

In [19]:
dataset["Review"] = LabelEncoder().fit_transform(dataset["Review"])

In [20]:
dataset.head()

Review                                               Text
0       3  I am coming to the borders and I will kill you...
1       3  im getting on borderlands and i will kill you ...
2       3  im coming on borderlands and i will murder you...
3       3  im getting on borderlands 2 and i will murder ...
4       3  im getting into borderlands and i can murder y...

In [21]:
dataset["Review"].value_counts()

1    22542
3    20831
2    18318
0    12990
Name: Review, dtype: int64

In [22]:
dataset.isna().sum()

Review      0
Text      686
dtype: int64

In [23]:
import re
import nltk
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [24]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

all_stopwords = stopwords.words('english')
all_stopwords.remove('not')

In [25]:
corpus = []
for i in range(0,74681):
    review = re.sub('[^a-zA-Z]',' ',str(dataset['Text'][i]))
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
    review = ' '.join(review)
    corpus.append(review)

In [26]:
corpus

['come border kill',
 'im get borderland kill',
 'im come borderland murder',
 'im get borderland murder',
 'im get borderland murder',
 'spent hour make someth fun know huge borderland fan maya one favorit charact decid make wallpap pc origin imag versu creation made enjoy pic twitter com mlsi wf jg',
 'spent coupl hour someth fun know huge borderland fan maya one favorit charact decid make wallpap pc origin pictur compar creation made fun pic twitter com mlsi wf jg',
 'spent hour someth fun know huge borderland fan maya one favorit charact',
 'spent hour make someth fun know huge rhandlerr fan maya one favorit charact decid make wallpap pc origin imag versu creation made enjoy pic twitter com mlsi wf jg',
 'spent hour make someth fun know huge rhandlerr fan maya one favorit charact decid make wallpap pc origin imag versu creation made enjoy pic twitter com mlsi wf jg',
 '',
 'rock hard la varlop rare power handsom jackpot borderland xbox dlvr rmtrgf',
 'rock hard la varlop rare power

In [27]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1420)

In [28]:
X = cv.fit_transform(corpus).toarray()
Y = dataset.iloc[:,-2].values

In [29]:
print(X)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [30]:
print(Y)

[3 3 3 ... 3 3 3]


In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.2, random_state = 42)

In [32]:
X.shape, X_train.shape

((74681, 1420), (59744, 1420))

# Model Training

In [33]:
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

In [34]:
modelNB = GaussianNB()
modelLR = LogisticRegression()
modelRF = RandomForestClassifier()
modelDT = DecisionTreeClassifier()
modelSVM = SVC()

In [35]:
modelNB.fit(X_train, Y_train)

GaussianNB()

In [36]:
modelLR.fit(X_train, Y_train)

c:\users\hp\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [37]:
modelRF.fit(X_train, Y_train)

RandomForestClassifier()

In [38]:
modelDT.fit(X_train, Y_train)

DecisionTreeClassifier()

modelSVM.fit(X_train, Y_train)

In [39]:
from sklearn.metrics import accuracy_score

In [40]:
predictionNB = modelNB.predict(X_test)

In [41]:
predictionLR = modelLR.predict(X_test)

In [42]:
predictionRF = modelRF.predict(X_test)

In [43]:
predictionDT = modelDT.predict(X_test)

predictionSVM = modelSVM.predict(X_test)

In [44]:
scoreNB = accuracy_score(predictionNB, Y_test)

In [45]:
scoreLR = accuracy_score(predictionLR, Y_test)

In [46]:
scoreRF = accuracy_score(predictionRF, Y_test)

In [47]:
scoreDT = accuracy_score(predictionDT, Y_test)

scoreSVM = accuracy_score(predictionSVM, Y_test)

In [50]:
scoreNB

0.42739505924884513

In [51]:
scoreLR

0.6013925152306353

In [52]:
scoreRF

0.8728660373568989

In [53]:
scoreDT

0.7941353685479012

# Prediction

In [54]:
user = input("Enter the text : ")
data = cv.transform([user]).toarray()
output = modelRF.predict(data)
print(output)
if output==0:
    print("Irrelevant")
elif output==1:
    print("Negative")
elif output==2:
    print("Neutral")
elif output==3:
    print("Positive")

Enter the text : open your wings and set the sky ablaze
[2]
Neutral
